// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HealthStatus struct {
	Status  string           `json:"status"`
	Details []*ServiceStatus `json:"details"`
}

type Message struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Sender    string `json:"sender"`
	Timestamp string `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type ServiceStatus struct {
	Service   string `json:"service"`
	Status    string `json:"status"`
	LastCheck string `json:"lastCheck"`
}

type Subscription struct {
}
