server:
  ip: "127.0.0.1"
  port: "8080"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "afnm640"
  dbname: "postgres"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

rabbitmq:
  username: "user"          # Username for RabbitMQ
  password: "pass"          # Password for RabbitMQ
  host: "localhost"         # Host address for RabbitMQ
  port: "5672"              # Port for RabbitMQ
  exchanges:
    currency: "currency_exchange"       # Exchange for currency updates
    user: "user_exchange"               # Exchange for user-related updates
    notifications: "notification_exchange" # Exchange for notifications

jwt:
  ssl: 
    admin:
      private_key: 
        - "internal"
        - "ssl"
        - "admin"
        - "private_key.pem"
      public_key: 
        - "internal"
        - "ssl"
        - "admin"
        - "public_key.pem"
    user:
      private_key: 
        - "internal"
        - "ssl"
        - "admin"
        - "private_key.pem"
      public_key: 
        - "internal"
        - "ssl"
        - "user"
        - "public_key.pem"
  issuer: "encrypted-db"
  access_token:
    expiration: 15 # minutes
  refresh_token:
    expiration: 10080 # minutes
  

otp:
  auth:
    name: "AUTH"
    ttl: 60 # seconds
    length: 6
    retry_limit: 3