definitions:
  models.APIResponse:
    properties:
      info:
        description: Info can hold any type of data (e.g., list or object)
      message:
        type: string
      status:
        type: integer
    type: object
  models.Currency:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      hk:
        type: string
      id:
        type: integer
      info:
        $ref: '#/definitions/models.CurrencyInfo'
      status:
        type: string
      updated_at:
        type: string
    type: object
  models.CurrencyInfo:
    properties:
      contract:
        type: string
      en_name:
        type: string
      fa_name:
        type: string
      if_fiat:
        type: boolean
      is_token:
        type: boolean
      symbol:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/currencies:
    post:
      consumes:
      - application/json
      description: Create a new currency in the system
      parameters:
      - description: Currency to create
        in: body
        name: currency
        required: true
        schema:
          $ref: '#/definitions/models.Currency'
      produces:
      - application/json
      responses:
        "0":
          description: 'URL Scheme Error: Ensure URL scheme is ''http'' or ''https'''
          schema:
            $ref: '#/definitions/models.APIResponse'
        "201":
          description: Currency created successfully
          schema:
            $ref: '#/definitions/models.APIResponse'
        "400":
          description: Invalid input or duplicate symbol/contract
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: Failed to create currency due to an unexpected error
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Create a new currency
      tags:
      - Admin
  /admin/currencies/{hk}:
    delete:
      description: Logically delete a currency by setting deleted_at and changing
        its status to 'deleted'.
      parameters:
      - description: Currency HK
        in: path
        name: hk
        required: true
        type: string
      responses:
        "200":
          description: Currency deleted successfully
          schema:
            $ref: '#/definitions/models.APIResponse'
        "404":
          description: Currency not found or already deleted
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: Failed to delete currency due to an unexpected error
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Delete a currency
      tags:
      - Admin
    put:
      consumes:
      - application/json
      description: Update the information or status of an existing currency using
        its HK (UUID) as identifier
      parameters:
      - description: Currency HK
        in: path
        name: hk
        required: true
        type: string
      - description: Currency data to update
        in: body
        name: currency
        required: true
        schema:
          $ref: '#/definitions/models.Currency'
      produces:
      - application/json
      responses:
        "200":
          description: Currency updated successfully
          schema:
            $ref: '#/definitions/models.APIResponse'
        "400":
          description: Invalid input or duplicate symbol/contract
          schema:
            $ref: '#/definitions/models.APIResponse'
        "404":
          description: Currency not found
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: Failed to update currency due to an unexpected error
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Update a currency
      tags:
      - Admin
  /public/currencies:
    get:
      description: Retrieve all active currencies from Redis cache
      produces:
      - application/json
      responses:
        "200":
          description: List of active currencies
          schema:
            items:
              $ref: '#/definitions/models.Currency'
            type: array
        "500":
          description: Failed to retrieve currencies from cache
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Get all active currencies
      tags:
      - Public
  /public/currencies/{hk}:
    get:
      description: Retrieve a single currency from Redis cache using its HK
      parameters:
      - description: Currency HK
        in: path
        name: hk
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Currency data
          schema:
            $ref: '#/definitions/models.Currency'
        "404":
          description: Currency not found
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: Failed to retrieve currency from cache
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Get a single currency by HK
      tags:
      - Public
swagger: "2.0"
